Server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/ycdidb
    driver-class-name: org.mariadb.jdbc.Driver
    username: ycdi
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto : create // 기존 테이블에 새 테이블이 덮어짐